//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub client_id: String,
    pub account: i64,
    pub leverage: i32,
    pub server: String,
    pub company: String,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub profit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub margin: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
