[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
http = { path = "../http" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.124"
async-trait = "0.1.81"